server:
  port: 9090
spring:
    book:
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: sa
      password: 
    user:
      datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbcUrl: jdbc:oracle:thin:@localhost:1521:ORCL
      password: manager
      username: system
        
    jpa:
      properties:
        hibernate:
        format_sql: true
      show-sql: true
  
