server:
  port: 1111

spring:  cloud:    config:      server:        git:          uri: https://github.com/TEK-Leads/Config-Properties.git          clone-on-start: true


#spring.cloud.config.server.git.cloneOnStart true
#management.security.enabled=false
