server:
  port: 9092

spring:  application:    name: admin-client-2
  boot:    admin:      client:        url: http://localhost:9090/

management:  endpoints:    web:      exposure:        include: "*"